# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63be4fd03bd563603d6ad78ad6d331d7e2b56a2fb01cc43c3818bae5c0f9c93f7c6f759968dfd55c3983f33bfb7528a99f3b848d993b15719e152ffeaac43280

test:
  secret_key_base: 20d1aaf38b5590c01e4784a7f69d58b12b0577e03deb69cf3a694ffe2e4d5aec8dff2e9a677ae7b39338ad51a5c0fc47d5de8b7739fb050c6720e1548c7e461a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
